import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  closeOfficeDocumentWithInvoker,
  getOfficeEngineStatusWithInvoker,
  type OfficeProgress,
  type ProgressChannel,
} from "../src/services/office-core.ts";

test("invokes the typed engine status command", async () => {
  let receivedCommand = "";
  let receivedArgs: Record<string, unknown> | undefined;
  const expected = { state: "ready" as const, version: "1.0.143" };
  const result = await getOfficeEngineStatusWithInvoker(
    async <T>(command: string, args?: Record<string, unknown>) => {
      receivedCommand = command;
      receivedArgs = args;
      return expected as T;
    },
  );

  assert.equal(receivedCommand, "get_office_engine_status");
  assert.equal(receivedArgs, undefined);
  assert.deepEqual(result, expected);
});

test("invokes close with a camelCase progress channel envelope", async () => {
  let receivedCommand = "";
  let receivedArgs: Record<string, unknown> | undefined;
  const channel: ProgressChannel<OfficeProgress> = { onmessage: null };
  const progressEvents: OfficeProgress[] = [];
  const request = { path: "/tmp/report.docx" };

  const result = await closeOfficeDocumentWithInvoker(
    async <T>(command: string, args?: Record<string, unknown>) => {
      receivedCommand = command;
      receivedArgs = args;
      return { succeeded: true } as T;
    },
    () => channel,
    request,
    (progress) => progressEvents.push(progress),
  );
  channel.onmessage?.({ stage: "closing" });
  channel.onmessage?.({ stage: "completed" });

  assert.equal(receivedCommand, "close_office_document");
  assert.deepEqual(receivedArgs, { request, onProgress: channel });
  assert.deepEqual(result, { succeeded: true });
  assert.deepEqual(progressEvents, [
    { stage: "closing" },
    { stage: "completed" },
  ]);
  assert.equal("binaryPath" in request, false);
  assert.equal("environment" in request, false);
  assert.equal("argv" in request, false);
});

test("registers only explicit Office permissions for the main window", async () => {
  const capabilityUrl = new URL(
    "../src-tauri/capabilities/default.json",
    import.meta.url,
  );
  const capability = JSON.parse(await readFile(capabilityUrl, "utf8")) as {
    permissions: string[];
  };

  assert.ok(capability.permissions.includes("allow-get-office-engine-status"));
  assert.ok(capability.permissions.includes("allow-close-office-document"));
  assert.equal(
    capability.permissions.some((permission) => permission.startsWith("shell:")),
    false,
  );

  const buildScript = await readFile(
    new URL("../src-tauri/build.rs", import.meta.url),
    "utf8",
  );
  const invokeHandler = await readFile(
    new URL("../src-tauri/src/lib.rs", import.meta.url),
    "utf8",
  );
  const statusPermission = await readFile(
    new URL(
      "../src-tauri/permissions/autogenerated/get_office_engine_status.toml",
      import.meta.url,
    ),
    "utf8",
  );
  const closePermission = await readFile(
    new URL(
      "../src-tauri/permissions/autogenerated/close_office_document.toml",
      import.meta.url,
    ),
    "utf8",
  );

  for (const command of [
    "get_office_engine_status",
    "close_office_document",
  ]) {
    assert.match(buildScript, new RegExp(`"${command}"`));
    assert.match(invokeHandler, new RegExp(`commands::office::${command}`));
  }
  assert.match(statusPermission, /commands\.allow = \["get_office_engine_status"\]/);
  assert.match(closePermission, /commands\.allow = \["close_office_document"\]/);
  assert.doesNotMatch(buildScript, /execute_office_cli/);
  assert.doesNotMatch(invokeHandler, /execute_office_cli/);
});
